pipeline{
    agent any
    stages{
        stage('Run Android Tests'){
            steps{
                sh "cucumber -p math_op PLATFORM_NAME='android'"
            }
        }
    }
    post{
        always{
            emailext attachmentsPattern: '${FILE, path="reports/report.html"}', body: 'See the attach' , mimeType: 'text/html', replyTo: 'no-reply@jenkins.com', subject: 'Email Report of Android Tests', to: 'foxraf3d@gmail.com;rafael_sistema27@hotmail.com'
        }
    }
}