pipeline{
    agent any
    stages{
        stage('Run Tests Android'){
            steps{
                sh "cucumber -p math_op PLATFORM_NAME='android'"
            }
        }  
    }
    post{
        always{
            emailext body: 'readFile("reports/report.html")', mimeType: 'text/html', replyTo: 'no-reply@jenkins.com', subject: 'Email Report of Android Tests', to: 'foxraf3d@gmail.com;rafael_sistema27@hotmail.com'
        } 
    }
}