pipeline{
    agent any
    stages{
        stage('Run Tests Android'){
            steps{
                sh "cucumber -p math_op PLATFORM_NAME='android'"
            }
        }  
    }
    post{
        always{
            emailext attachmentsPattern: ' ${FILE,path=”reports/report.html”}', body: 'See the report of android build', subject: 'Seending Reports - Android', to: 'foxraf3d@gmail.com;rafael_sistema27@hotmail.com'
        } 
    }
}